const quizQuestions=[
  {articleId:1,range:"1-300",articleTitle:"我的家庭",question:"บทความนี้พูดถึงอะไร?",options:["ครอบครัว","โรงเรียน","การท่องเที่ยว","งานอดิเรก"],answer:0,answerText:"ครอบครัว"},
  {articleId:2,range:"1-300",articleTitle:"学校生活",question:"ในบทความ ผู้เขียนเรียนภาษาอะไรที่มหาวิทยาลัย?",options:["อังกฤษ","ญี่ปุ่น","ภาษาจีน","เกาหลี"],answer:2,answerText:"ภาษาจีน"},
  {articleId:3,range:"1-300",articleTitle:"去中国旅行",question:"ผู้เขียนตั้งใจจะไปเที่ยวที่ไหน?",options:["เซี่ยงไฮ้","ปักกิ่ง","กวางโจว","เสิ่นเจิ้น"],answer:1,answerText:"ปักกิ่ง"},
  {articleId:4,range:"1-300",articleTitle:"我的爱好",question:"งานอดิเรกของผู้เขียนคืออะไร?",options:["เล่นฟุตบอล","เล่นบาสเกตบอล","เล่นเทนนิส","ว่ายน้ำ"],answer:1,answerText:"เล่นบาสเกตบอล"},
  {articleId:5,range:"1-300",articleTitle:"工作环境",question:"ผู้เขียนทำงานที่ไหน?",options:["ร้านอาหาร","บริษัท","โรงพยาบาล","โรงเรียน"],answer:1,answerText:"บริษัท"},
  {articleId:6,range:"1-300",articleTitle:"健康习惯",question:"สิ่งใดที่เป็นอันตรายต่อสุขภาพตามบทความ?",options:["การออกกำลังกาย","การกินผลไม้","การสูบบุหรี่","การนอนตรงเวลา"],answer:2,answerText:"การสูบบุหรี่"},
  {articleId:7,range:"1-300",articleTitle:"购物经验",question:"ผู้เขียนไปซื้อของที่ไหน?",options:["ตลาด","ห้างสรรพสินค้า","ซูเปอร์มาร์เก็ต","ร้านค้า"],answer:2,answerText:"ซูเปอร์มาร์เก็ต"},
  {articleId:8,range:"1-300",articleTitle:"我的城市",question:"ผู้เขียนอาศัยอยู่ในเมืองขนาดใด?",options:["เมืองเล็ก","เมืองกลาง","เมืองใหญ่","เมืองชายแดน"],answer:2,answerText:"เมืองใหญ่"},
  {articleId:9,range:"1-300",articleTitle:"餐厅经历",question:"ผู้เขียนและเพื่อนสั่งอาหารอะไร?",options:["ข้าวผัด","ไข่ บะหมี่ และเบียร์","ต้มยำ","สเต็ก"],answer:1,answerText:"ไข่ บะหมี่ และเบียร์"},
  {articleId:10,range:"1-300",articleTitle:"一次聚会",question:"ในงานเลี้ยง ทุกคนทำอะไร?",options:["ดูหนัง","ร้องเพลง เต้นรำ ดื่มเบียร์","เล่นเกม","คุยเล่น"],answer:1,answerText:"ร้องเพลง เต้นรำ ดื่มเบียร์"},
  {articleId:11,range:"1-300",articleTitle:"学习方法",question:"สิ่งใดที่ช่วยพัฒนาภาษาพูด?",options:["อ่านหนังสือ","ฝึกบทสนทนา","ฟังเพลง","ดูหนัง"],answer:1,answerText:"ฝึกบทสนทนา"},
  {articleId:12,range:"1-300",articleTitle:"看病经历",question:"ผู้เขียนป่วยอะไร?",options:["ปวดหัว","ปวดท้อง","ไข้","ไอ"],answer:1,answerText:"ปวดท้อง"},
  {articleId:13,range:"1-300",articleTitle:"周末计划",question:"ผู้เขียนตั้งใจจะไปไหนสุดสัปดาห์?",options:["ชายหาด","ปีนเขา","ช้อปปิ้ง","พักผ่อนที่บ้าน"],answer:1,answerText:"ปีนเขา"},
  {articleId:14,range:"1-300",articleTitle:"我的家乡",question:"บ้านเกิดของผู้เขียนอยู่ทางทิศใด?",options:["ทิศตะวันตก","ทิศตะวันออก","ทิศเหนือ","ทิศใต้"],answer:1,answerText:"ทิศตะวันออก"},
  {articleId:15,range:"1-300",articleTitle:"找工作",question:"ผู้เขียนเริ่มหางานเมื่อไหร?",options:["ก่อนจบมหาวิทยาลัย","หลังจบมหาวิทยาลัย","ขณะเรียน","ไม่ได้หางาน"],answer:1,answerText:"หลังจบมหาวิทยาลัย"},
  {articleId:16,range:"1-300",articleTitle:"一次误会",question:"เหตุผลที่ทำให้เกิดความเข้าใจผิดคืออะไร?",options:["เพื่อนลืมนัด","ผู้เขียนลืมนัด","ทั้งคู่มาสาย","ไม่ได้นัดกัน"],answer:0,answerText:"เพื่อนลืมนัด"},
  {articleId:17,range:"1-300",articleTitle:"天气变化",question:"ช่วงนี้อากาศเปลี่ยนแปลงอย่างไร?",options:["เปลี่ยนน้อย","เปลี่ยนมาก","ไม่เปลี่ยน","เปลี่ยนเล็กน้อย"],answer:1,answerText:"เปลี่ยนมาก"},
  {articleId:18,range:"1-300",articleTitle:"使用电梯",question:"ผู้เขียนทำงานชั้นที่เท่าไหร่?",options:["ชั้นสิบ","ชั้นยี่สิบ","ชั้นสามสิบ","ชั้นสี่สิบ"],answer:1,answerText:"ชั้นยี่สิบ"},
  {articleId:19,range:"1-300",articleTitle:"动物园",question:"ผู้เขียนไปสวนสัตว์กับใคร?",options:["พี่ชาย","น้องชาย","พี่สาว","เพื่อน"],answer:1,answerText:"น้องชาย"},
  {articleId:20,range:"1-300",articleTitle:"保护环境",question:"สิ่งใดที่เราไม่ควรทำตามบทความ?",options:["ปลูกต้นไม้","ทิ้งขยะทุกที่","รักษาโลก","ประหยัดพลังงาน"],answer:1,answerText:"ทิ้งขยะทุกที่"},
  {articleId:31,range:"301-600",articleTitle:"发展经济",question:"บทความนี้พูดถึงอะไร?",options:["การพัฒนาเศรษฐกิจ","การศึกษา","การท่องเที่ยว","การกีฬา"],answer:0,answerText:"การพัฒนาเศรษฐกิจ"},
  {articleId:32,range:"301-600",articleTitle:"学习进步",question:"การทบทวนบทเรียนมีความสำคัญอย่างไร?",options:["ไม่สำคัญ","สำคัญมาก","สำคัญน้อย","ไม่แน่ใจ"],answer:1,answerText:"สำคัญมาก"},
  {articleId:33,range:"301-600",articleTitle:"日常生活",question:"สภาพแวดล้อมที่สะอาดทำให้รู้สึกอย่างไร?",options:["ไม่สบาย","สบาย","เฉยๆ","รำคาญ"],answer:1,answerText:"สบาย"},
  {articleId:34,range:"301-600",articleTitle:"工作态度",question:"ควรทำงานอย่างไร?",options:["เกียจคร้าน","ตั้งใจ","ไม่สนใจ","หลีกเลี่ยง"],answer:1,answerText:"ตั้งใจ"},
  {articleId:35,range:"301-600",articleTitle:"社交活动",question:"ผู้เขียนเข้าร่วมกิจกรรมอะไร?",options:["กิจกรรมทุกประเภท","กิจกรรมกีฬา","กิจกรรมศิลปะ","กิจกรรมการศึกษา"],answer:0,answerText:"กิจกรรมทุกประเภท"},
  {articleId:61,range:"601-900",articleTitle:"旅游经历",question:"การท่องเที่ยวทำให้คนรู้สึกอย่างไร?",options:["เครียด","ผ่อนคลาย","เศร้า","โกรธ"],answer:1,answerText:"ผ่อนคลาย"},
  {articleId:62,range:"601-900",articleTitle:"科技发展",question:"เทคโนโลยีทำให้ชีวิตเปลี่ยนแปลงอย่างไร?",options:["ไม่เปลี่ยน","เปลี่ยนน้อย","เปลี่ยนมาก","ไม่แน่ใจ"],answer:2,answerText:"เปลี่ยนมาก"},
  {articleId:63,range:"601-900",articleTitle:"环境保护",question:"ทุกคนมีหน้าที่อะไร?",options:["ทำลายสิ่งแวดล้อม","ปกป้องสิ่งแวดล้อม","ไม่สนใจ","ละเลย"],answer:1,answerText:"ปกป้องสิ่งแวดล้อม"},
  {articleId:64,range:"601-900",articleTitle:"文化交流",question:"การเข้าใจวัฒนธรรมที่แตกต่างช่วยอะไร?",options:["ไม่ช่วยอะไร","ช่วยสื่อสาร","ช่วยสร้างสันติภาพ","ทั้งกและข้อ 2 และ 3"],answer:3,answerText:"ทั้งกและข้อ 2 และ 3"},
  {articleId:65,range:"601-900",articleTitle:"健康生活",question:"กิจวัตรที่สม่ำเสมอช่วยอะไร?",options:["ทำให้ป่วย","ทำให้สุขภาพดี","ไม่มีผล","ทำให้เหนื่อย"],answer:1,answerText:"ทำให้สุขภาพดี"},
  {articleId:91,range:"901-1200",articleTitle:"职业发展",question:"การวางแผนอาชีพสำคัญอย่างไร?",options:["ไม่สำคัญ","สำคัญมาก","สำคัญน้อย","ไม่แน่ใจ"],answer:1,answerText:"สำคัญมาก"},
  {articleId:92,range:"901-1200",articleTitle:"人际关系",question:"การปฏิบัติต่อผู้อื่นควรทำอย่างไร?",options:["ด้วยความจริงใจ","ด้วยความหลอกลวง","ไม่สนใจ","ด้วยความโกรธ"],answer:0,answerText:"ด้วยความจริงใจ"},
  {articleId:93,range:"901-1200",articleTitle:"时间管理",question:"การจัดเวลาอย่างสมเหตุสมผลช่วยอะไร?",options:["ทำให้เสียเวลา","ทำให้มีประสิทธิภาพ","ไม่มีผล","ทำให้เหนื่อย"],answer:1,answerText:"ทำให้มีประสิทธิภาพ"},
  {articleId:94,range:"901-1200",articleTitle:"学习态度",question:"ความมุ่งมั่นช่วยอะไร?",options:["ทำให้ล้มเหลว","ทำให้สำเร็จ","ไม่มีผล","ทำให้อ่อนผ่อน"],answer:1,answerText:"ทำให้สำเร็จ"},
  {articleId:95,range:"901-1200",articleTitle:"生活智慧",question:"รู้จักพอใจช่วยให้มีอะไร?",options:["ความทุกข์","ความสุข","ความโกรธ","ความเศร้า"],answer:1,answerText:"ความสุข"}
];
